name: Deploy to Vercel (Production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_jf00Jpfp6cElvXAfxaxVal0Q
          VERCEL_PROJECT_ID: prj_9K8sZjhPJAjOBi4RztzjG2ewckAI
